drop table if exists product;
drop table if exists category;

create table category(
	id int generated by default as IDENTITY(start with 1) primary key not null,
	name varchar(20) not null
);

create table product(
	id int generated by default as IDENTITY(start with 1) primary key not null,
	name varchar(40) not null,
	category_id int not null,
	private int not null,
	foreign key (category_id) references category(id)
);